define({
  root: (
    { _widgetLabel: "Zoomer"
    , selectZoomMode: "Select zoom mode"
    , countyZoom: "Please select the county from the list and click on the Zoom button."
    , boundaryZoom: "Please select a boundary from the list and click on the Zoom button."
    , cityZoom: "To zoom to a city, please select the city from the drop down list. If you want to go to a specific address within that city, please enter that street address as well."
    , legislativeZoom: "Please select a legislative district from the list below and click on the Zoom button."
    , projectZoom: "Please select a project-level category from the list below and click on the Zoom button."
    , districtZoom: "Please select a UDOT region from the list below and click on the Zoom button. Based on your region selection, you may also select a maintenance station within."
    , routesZoom: "Please select a route from the list below and click on the Zoom button. Route selection will also return projects on cross streets intersected by the route."
    , filterdata: "Filter Attribute Table Data"
    , messageProvo: "Provo? Just like Bielefeld, there is no such thing."
    , btnZoom: "Zoom"
    , btnReset: "Reset"
    , btnShare: "Share"
    , city: "City"
    , address: "Address"
    , region: "Region"
    , county: "County"
    , station: "Maintenance Station"
    , project: "Project-level category"
    , programManager: "Program Manager"
    , UDOTResidentEngineer: "UDOT Resident Engineer"
    , consultantResidentEngineer: "Consultant Resident Engineer"
    , shareExtent: "You can share the current zoom extent by using the URL below."
    , route: "Route"
    , interchange: "Interchange"
    , ramp: "Ramp"
    , btnFilterByPolygon: "Filter by Polygon"
    , urbanArea: "Urban Area Boundary"
    , urbanClusterSmallUrban: "Urban Cluster / Small Urban"
    , metropolitanPlanningOrganization: "Metropolitan Planning Organization"
    , ruralPlanningOrganization: "Rural Planning Organization"
    })
});