define({
  root: ({
    general: "General"
  , linkToAttributeTable: "Include check box to interface Zoomer widget selection with the Attribute Table widget."
  , eastereggProvo: "Include the Provo conspiracy."
  , udotPmAndRe: "Include the UDOT PM and RE filter."
  , spatialReference: "Spatial Reference"
  , agrc: "AGRC"
  , agrcAPIURL: "AGRC API URL"
  , agrcAPIKey: "AGRC API Key"
  , agrcAPICityFeatureClass: "City Feature Class"
  , agrcAPICountyFeatureClass: "County Feature Class"
  , agrcAPIStateHouseFeatureClass: "State House Feature Class"
  , agrcAPIStateSenateFeatureClass: "State Senate Feature Class"
  , agrcAPIUSCongressFeatureClass: "US Congress Feature Class"
  , bitly: "Bitly"
  , bitlyUse: "Use Bitly"
  , bitlyAPIKey: "Bitly API Key"
  , bitlyBaseURL: "Bitly Base URL"
  , bitlyBaseURLDesc: "The client's browser URL is used for the Bitly service, unless a Base URL is entered here"
  , proxy: "Proxy"
  , proxyUrl: "Proxy URL"
  , proxyMapsUDOT: "Use the proxy flag for the UDOT Maps Server."
  , proxyBitly: "Use the proxy flag for the Bitly API."
  , proxyAGRC: "Use the proxy flag for the AGRC API."
  })
});